#stup-app.yml
---
  - hosts: webservers
    become: true
    vars:
      path_to_app: "/var/www/html"
    tasks:
      - name: Uploading application file
        copy:
          src: ../index.php
          dest: "{{ path_to_app }}"
          mode: 0755
        tags: upload  
      - name: Create Simple info page
        copy:
          dest: "{{ path_to_app }}/info.php"
          content: "<h1> Information about the webserver {{ ansible_hostname }} </h1>"
        tags: create      

      - name: Configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'
        notify: Restart apache   # notify to restart apache only found changes on php.ini file
    handlers:
      - name: Restart apache
        service: name=httpd state=restarted        